name: duped
'on':
  push:
    branches:
      - main
      - releases/**
jobs:
  dupable:
    runs-on: ubuntu-20.04
    steps:
      - name: proof of dupe
        run: echo "notice that this workflow has ran twice"